# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'AppEngineDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppEngineDemo

  pod 'SVProgressHUD'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SnapKit'
  pod 'CryptoSwift'
  pod 'IQKeyboardManager'
  pod 'ObjectMapper'

end
